# This will be retured by switchboard when get '*' is requested

[switchboard]
ip = "x.x.x.x"
method = "set"       # Possible values --> set/get. What if you don't want to set everything. May be -ve values ?
[switchboard.1]
status = 0
slider = 20

[switchboard.2]
status = 0
slider = 20

[switchboard.3]
status = 0
slider = 20

[switchboard.4]
status = 0
slider = 20
