site_name: SWITCH-CASE
repo_url: https://github.com/kteza1/switch-case
site_description: A smart switch board for your home
site_favicon: favicon.ico
theme: readthedocs
    
pages:
- INTRODUCTION: index.md
- GETTING STARTED:
    - Installing Sming: getting-started/INSTALLING SMING.md
    - Accessing Serial Port: getting-started/ACCESSING SERIAL PORT.md
    - Installing Vagrant: getting-started/VAGRANT_SETUP.md
- SOFTWARE DESIGN:
    - Mqtt connection: communication/connection.md
    - Mqtt discovery and Control: communication/discovery_and_control.md
